// Copyright 2026 PingCAP, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/discovery/pb/tidb_discovery.proto

// The proto package name determines the gRPC full method names
// (e.g. /tidb_discoverypb.TiDBDiscovery/Subscribe) and MUST stay stable:
// the server side may migrate into PD (as a microservice) in the future and
// only the go_package option and Go imports would change then, keeping the
// wire protocol identical.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TiDBDiscovery_Subscribe_FullMethodName = "/tidb_discoverypb.TiDBDiscovery/Subscribe"
)

// TiDBDiscoveryClient is the client API for TiDBDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TiDBDiscoveryClient interface {
	// Subscribe is a long-lived stream. The server always sends a full
	// snapshot first (full=true) and then deltas (full=false).
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (TiDBDiscovery_SubscribeClient, error)
}

type tiDBDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewTiDBDiscoveryClient(cc grpc.ClientConnInterface) TiDBDiscoveryClient {
	return &tiDBDiscoveryClient{cc}
}

func (c *tiDBDiscoveryClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (TiDBDiscovery_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &TiDBDiscovery_ServiceDesc.Streams[0], TiDBDiscovery_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tiDBDiscoverySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TiDBDiscovery_SubscribeClient interface {
	Recv() (*DiscoveryResponse, error)
	grpc.ClientStream
}

type tiDBDiscoverySubscribeClient struct {
	grpc.ClientStream
}

func (x *tiDBDiscoverySubscribeClient) Recv() (*DiscoveryResponse, error) {
	m := new(DiscoveryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TiDBDiscoveryServer is the server API for TiDBDiscovery service.
// All implementations must embed UnimplementedTiDBDiscoveryServer
// for forward compatibility
type TiDBDiscoveryServer interface {
	// Subscribe is a long-lived stream. The server always sends a full
	// snapshot first (full=true) and then deltas (full=false).
	Subscribe(*SubscribeRequest, TiDBDiscovery_SubscribeServer) error
	mustEmbedUnimplementedTiDBDiscoveryServer()
}

// UnimplementedTiDBDiscoveryServer must be embedded to have forward compatible implementations.
type UnimplementedTiDBDiscoveryServer struct {
}

func (UnimplementedTiDBDiscoveryServer) Subscribe(*SubscribeRequest, TiDBDiscovery_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTiDBDiscoveryServer) mustEmbedUnimplementedTiDBDiscoveryServer() {}

// UnsafeTiDBDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TiDBDiscoveryServer will
// result in compilation errors.
type UnsafeTiDBDiscoveryServer interface {
	mustEmbedUnimplementedTiDBDiscoveryServer()
}

func RegisterTiDBDiscoveryServer(s grpc.ServiceRegistrar, srv TiDBDiscoveryServer) {
	s.RegisterService(&TiDBDiscovery_ServiceDesc, srv)
}

func _TiDBDiscovery_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TiDBDiscoveryServer).Subscribe(m, &tiDBDiscoverySubscribeServer{stream})
}

type TiDBDiscovery_SubscribeServer interface {
	Send(*DiscoveryResponse) error
	grpc.ServerStream
}

type tiDBDiscoverySubscribeServer struct {
	grpc.ServerStream
}

func (x *tiDBDiscoverySubscribeServer) Send(m *DiscoveryResponse) error {
	return x.ServerStream.SendMsg(m)
}

// TiDBDiscovery_ServiceDesc is the grpc.ServiceDesc for TiDBDiscovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TiDBDiscovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tidb_discoverypb.TiDBDiscovery",
	HandlerType: (*TiDBDiscoveryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TiDBDiscovery_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/discovery/pb/tidb_discovery.proto",
}
