// Copyright 2026 PingCAP, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/discovery/pb/tidb_discovery.proto

// The proto package name determines the gRPC full method names
// (e.g. /tidb_discoverypb.TiDBDiscovery/Subscribe) and MUST stay stable:
// the server side may migrate into PD (as a microservice) in the future and
// only the go_package option and Go imports would change then, keeping the
// wire protocol identical.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by keyspaces. Empty means all keyspaces.
	// Reserved: the server ignores it and broadcasts everything for now.
	Keyspaces []string `protobuf:"bytes,1,rep,name=keyspaces,proto3" json:"keyspaces,omitempty"`
	// The revision that the client already has, used as a resume hint.
	// 0 means the client needs a full snapshot.
	// Reserved: the server ignores it and always sends a full snapshot on
	// (re)connect for now.
	KnownRevision int64 `protobuf:"varint,2,opt,name=known_revision,json=knownRevision,proto3" json:"known_revision,omitempty"`
	// The identity of the client, only for logging and metrics.
	ClientId      string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_discovery_pb_tidb_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetKeyspaces() []string {
	if x != nil {
		return x.Keyspaces
	}
	return nil
}

func (x *SubscribeRequest) GetKnownRevision() int64 {
	if x != nil {
		return x.KnownRevision
	}
	return 0
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The etcd revision that this response is derived from, monotonic per hub.
	Revision int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// full=true: replace the whole local cache with `upserted`.
	// full=false: apply `upserted` and `removed_addrs` as a delta.
	Full     bool            `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	Upserted []*TiDBInstance `protobuf:"bytes,3,rep,name=upserted,proto3" json:"upserted,omitempty"`
	// Addresses ("ip:port") of the instances that are gone.
	RemovedAddrs []string `protobuf:"bytes,4,rep,name=removed_addrs,json=removedAddrs,proto3" json:"removed_addrs,omitempty"`
	// The Prometheus of the cluster, piggy-backed when it changes.
	Prometheus    *PrometheusInfo `protobuf:"bytes,5,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_discovery_pb_tidb_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DiscoveryResponse) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *DiscoveryResponse) GetUpserted() []*TiDBInstance {
	if x != nil {
		return x.Upserted
	}
	return nil
}

func (x *DiscoveryResponse) GetRemovedAddrs() []string {
	if x != nil {
		return x.RemovedAddrs
	}
	return nil
}

func (x *DiscoveryResponse) GetPrometheus() *PrometheusInfo {
	if x != nil {
		return x.Prometheus
	}
	return nil
}

type TiDBInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// addr is the "ip:port" SQL address and is the cache key.
	Addr          string            `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Ip            string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	StatusPort    uint32            `protobuf:"varint,3,opt,name=status_port,json=statusPort,proto3" json:"status_port,omitempty"`
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Keyspace      string            `protobuf:"bytes,5,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Version       string            `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TiDBInstance) Reset() {
	*x = TiDBInstance{}
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TiDBInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiDBInstance) ProtoMessage() {}

func (x *TiDBInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiDBInstance.ProtoReflect.Descriptor instead.
func (*TiDBInstance) Descriptor() ([]byte, []int) {
	return file_pkg_discovery_pb_tidb_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *TiDBInstance) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *TiDBInstance) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *TiDBInstance) GetStatusPort() uint32 {
	if x != nil {
		return x.StatusPort
	}
	return 0
}

func (x *TiDBInstance) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TiDBInstance) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *TiDBInstance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PrometheusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	BinaryPath    string                 `protobuf:"bytes,3,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrometheusInfo) Reset() {
	*x = PrometheusInfo{}
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrometheusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrometheusInfo) ProtoMessage() {}

func (x *PrometheusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discovery_pb_tidb_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrometheusInfo.ProtoReflect.Descriptor instead.
func (*PrometheusInfo) Descriptor() ([]byte, []int) {
	return file_pkg_discovery_pb_tidb_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *PrometheusInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PrometheusInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PrometheusInfo) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

var File_pkg_discovery_pb_tidb_discovery_proto protoreflect.FileDescriptor

const file_pkg_discovery_pb_tidb_discovery_proto_rawDesc = "" +
	"\n" +
	"%pkg/discovery/pb/tidb_discovery.proto\x12\x10tidb_discoverypb\"t\n" +
	"\x10SubscribeRequest\x12\x1c\n" +
	"\tkeyspaces\x18\x01 \x03(\tR\tkeyspaces\x12%\n" +
	"\x0eknown_revision\x18\x02 \x01(\x03R\rknownRevision\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"\xe6\x01\n" +
	"\x11DiscoveryResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x12:\n" +
	"\bupserted\x18\x03 \x03(\v2\x1e.tidb_discoverypb.TiDBInstanceR\bupserted\x12#\n" +
	"\rremoved_addrs\x18\x04 \x03(\tR\fremovedAddrs\x12@\n" +
	"\n" +
	"prometheus\x18\x05 \x01(\v2 .tidb_discoverypb.PrometheusInfoR\n" +
	"prometheus\"\x88\x02\n" +
	"\fTiDBInstance\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1f\n" +
	"\vstatus_port\x18\x03 \x01(\rR\n" +
	"statusPort\x12B\n" +
	"\x06labels\x18\x04 \x03(\v2*.tidb_discoverypb.TiDBInstance.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bkeyspace\x18\x05 \x01(\tR\bkeyspace\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x0ePrometheusInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1f\n" +
	"\vbinary_path\x18\x03 \x01(\tR\n" +
	"binaryPath2g\n" +
	"\rTiDBDiscovery\x12V\n" +
	"\tSubscribe\x12\".tidb_discoverypb.SubscribeRequest\x1a#.tidb_discoverypb.DiscoveryResponse0\x01B-Z+github.com/pingcap/tiproxy/pkg/discovery/pbb\x06proto3"

var (
	file_pkg_discovery_pb_tidb_discovery_proto_rawDescOnce sync.Once
	file_pkg_discovery_pb_tidb_discovery_proto_rawDescData []byte
)

func file_pkg_discovery_pb_tidb_discovery_proto_rawDescGZIP() []byte {
	file_pkg_discovery_pb_tidb_discovery_proto_rawDescOnce.Do(func() {
		file_pkg_discovery_pb_tidb_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_discovery_pb_tidb_discovery_proto_rawDesc), len(file_pkg_discovery_pb_tidb_discovery_proto_rawDesc)))
	})
	return file_pkg_discovery_pb_tidb_discovery_proto_rawDescData
}

var file_pkg_discovery_pb_tidb_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_discovery_pb_tidb_discovery_proto_goTypes = []any{
	(*SubscribeRequest)(nil),  // 0: tidb_discoverypb.SubscribeRequest
	(*DiscoveryResponse)(nil), // 1: tidb_discoverypb.DiscoveryResponse
	(*TiDBInstance)(nil),      // 2: tidb_discoverypb.TiDBInstance
	(*PrometheusInfo)(nil),    // 3: tidb_discoverypb.PrometheusInfo
	nil,                       // 4: tidb_discoverypb.TiDBInstance.LabelsEntry
}
var file_pkg_discovery_pb_tidb_discovery_proto_depIdxs = []int32{
	2, // 0: tidb_discoverypb.DiscoveryResponse.upserted:type_name -> tidb_discoverypb.TiDBInstance
	3, // 1: tidb_discoverypb.DiscoveryResponse.prometheus:type_name -> tidb_discoverypb.PrometheusInfo
	4, // 2: tidb_discoverypb.TiDBInstance.labels:type_name -> tidb_discoverypb.TiDBInstance.LabelsEntry
	0, // 3: tidb_discoverypb.TiDBDiscovery.Subscribe:input_type -> tidb_discoverypb.SubscribeRequest
	1, // 4: tidb_discoverypb.TiDBDiscovery.Subscribe:output_type -> tidb_discoverypb.DiscoveryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_discovery_pb_tidb_discovery_proto_init() }
func file_pkg_discovery_pb_tidb_discovery_proto_init() {
	if File_pkg_discovery_pb_tidb_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_discovery_pb_tidb_discovery_proto_rawDesc), len(file_pkg_discovery_pb_tidb_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_discovery_pb_tidb_discovery_proto_goTypes,
		DependencyIndexes: file_pkg_discovery_pb_tidb_discovery_proto_depIdxs,
		MessageInfos:      file_pkg_discovery_pb_tidb_discovery_proto_msgTypes,
	}.Build()
	File_pkg_discovery_pb_tidb_discovery_proto = out.File
	file_pkg_discovery_pb_tidb_discovery_proto_goTypes = nil
	file_pkg_discovery_pb_tidb_discovery_proto_depIdxs = nil
}
